@startuml class-diagram

class Biblioteca {
    - std::vector<std::shared_ptr<Recurso>> recursos

    + void agregarRecurso(std::shared_ptr<Recurso> recurso)
    + std::shared_ptr<Recurso> buscarRecursoPorId(int id) const
    + bool eliminarRecursoPorId(int id)
    + int contarRecursos() const
    + int contarLibros() const
    + int contarRevistas() const
    + std::vector<std::shared_ptr<Recurso>> obtenerLibros() const
    + std::vector<std::shared_ptr<Recurso>> obtenerRevistas() const
    + std::vector<std::shared_ptr<Recurso>> obtenerRecursos() const
}

class Recurso {
    # std::string contenido
    # int id
    # std::string titulo

    + Recurso(std::string contenido, int id, std::string titulo)
    + std::string getContenido() const
    + int getId() const
    + std::string getTitulo() const
    + void setContenido(std::string contenido)
    + void setId(int nuevoId)
    + void setTitulo(std::string titulo)
    + virtual std::string toString() const = 0
    + virtual ~Recurso()
}

class Libro {
    - std::string genero
    - int edicion
    - std::string autor
    
    + Libro(std::string& contenido, int id, std::string& titulo, std::string& genero, int edicion, std::string& autor)
    + std::string toString() const
    + std::string getGenero() const
    + int getEdicion() const
    + std::string getAutor() const 
    + void setGenero(std::string genero)
    + void setEdicion(int edicion)
    + void setAutor(std::string autor)
}

class Revista {
    - std::string periodicidad
    - int numEjemplar
    - std::string tema

    + Revista(std::string& contenido, int id, std::string& titulo, std::string& periodicidad, int numEjemplar, std::string& tema)
    + std::string toString() const
    + std::string getPeriodicidad() const 
    + int getEjemplar() const 
    + std::string getTema() const 
    + void setPeriodicidad(std::string periodicidad)
    + void setEjemplar(int numEjemplar)
    + void setTema(std::string tema)
}

class Interfaz {
    - Biblioteca biblioteca

    + void ejecutar()
    - void mostrarMenu()
    - void limpiarInput()
    - void crearLibro()
    - void crearRevista()
}

Recurso <|-- Libro
Recurso <|-- Revista
Biblioteca o-- "1..*" Recurso
Interfaz *-- "1" Biblioteca

@enduml
